### ISSUE TITLE
Write further guidance on scctemplate: index yaml

### ISSUE THREAD

**Issue by thomaszwagerman** [SCC-Planning/scctemplate#2]
The yaml for each index.rmd file in this package requires extra arguments to create website navigation.

``` yaml
---
title: "Example Website Homepage"
scctemplate:
  index:
    - href: "example.html"
      text: "Example Page"
    - href: "another_example.html"
      text: "Another example page"
---
```

Most rmarkdown website will have this information under a navbar argument. However, the SCC website does not use a navbar, making it a bit tricky to program for a markdown website.

By creating a custom scctemplate: index: argument I work around this issue. However, some documentation should be written to make this use clear.
